class Disease(object):

    name = ""
    buwei = ""
    keshi = ""
    yongyao = ""
    question = ""
    anwser = ""
    binyin = ""
    zhengzhuang = ""
    jiancha = ""
    yufang = ""
    zhiliao = ""
    jianbie = ""
    binfazheng = ""
    img=""